# Generated by Django 4.2.2 on 2023-06-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('product', models.CharField(max_length=256, null=True, unique=True)),
                ('slug', models.SlugField(max_length=256, unique=True)),
                ('description', models.TextField(max_length=512)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('images', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
