# Generated by Django 4.2.2 on 2023-06-27 10:00

import apps.orders.models
from django.db import migrations
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=enumchoicefield.fields.EnumChoiceField(default=apps.orders.models.Status(2), enum_class=apps.orders.models.Status, max_length=20),
        ),
    ]
